### ISSUE TITLE
QA for dynamic time label

### ISSUE THREAD

**Issue by wannacfuture** [wannacfuture/Battleship#85]
1. Design new Landing page
2. Other tasks

Ensure more ....

**Comment by fei-max** [comment]
In the garden of existence, each individual is a unique flower, contributing to the symphony of colors, scents, and textures. With every challenge you overcome, you bloom with more resilience and beauty. May you continue to grow, embracing both the rain and sunshine, knowing that each plays a crucial role in your journey of blossoming

**Comment by fei-max** [comment]
We should periodically backup the bot's prod DB in case something goes wrong.

What should be done:

Create a private github repository for DB backups
Create a workflow that will dump (both schema and data) the bot's prod DB once a day ([example](https://supabase.com/docs/guides/cli/github-action/backups#periodic-backups-workflow))
Try to recover the DB from a generated dump in order to check that it works

**Comment by wannacfuture** [comment]
Let me take a look.
